freebsd_instance:
  image_family: freebsd-14-1

freebsd_task:
  env:
    matrix:
      - OCAML_VERSION: 4.13.1
      - OCAML_VERSION: 4.14.2

  pkg_install_script: pkg install -y ocaml-opam gmp gmake pkgconf bash ca_root_nss

  ocaml_script:
    - opam init -a --comp=$OCAML_VERSION
    - opam env

  pin_packages_script:
    - opam pin add -y -t --with-version=dev happy-eyeballs.opam .
    - opam pin add -y -t --with-version=dev happy-eyeballs-lwt.opam .
    - opam pin add -y -t --with-version=dev happy-eyeballs-mirage.opam .

  build_script:
    - opam exec -- dune build -p happy-eyeballs,happy-eyeballs-lwt,happy-eyeballs-mirage
